#  Name of workflow
name: Generate a build and push to another branch

# When workflow is triggered
on:
  push:
    branches:
      - main

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    name: Build and Push
    # Steps in job
    steps:
        # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v4.1.0
      # Install NodeJS
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      # Run npm install and build on our code
      - name: Install all dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
        # Run Tests
    #   - name: Test
    #     run: npm run test if-present
      # Deploy to Hostinger using our production secrets
      - name: Deploy to Hostinger
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build  #build artifacts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
          VITE_RAWG_API_KEY: ${{ secrets.VITE_RAWG_API_KEY }}
